const cactusTips = [
  "Tip: Water slowly until the soil feels damp, then check again in an hour.",
  "Tip: Cacti prefer to dry out completely between waterings.",
  "Tip: During winter, most cacti need very little water — once a month or less.",
  "Tip: Make sure your pot has a drainage hole so roots don't sit in water.",
  "Tip: Bright indirect light is ideal for most indoor cacti.",
  "Tip: A south- or east-facing window usually gives the best light indoors.",
  "Tip: If you're unsure whether to water, wait another day.",
  "Tip: Yellow or mushy stems usually mean overwatering, not underwatering.",
  "Tip: Cacti like well-draining soil — mix in perlite or coarse sand.",
  "Tip: Repot your cactus every two to three years to refresh the soil.",
  "Tip: A slightly snug pot is better than a large one — too much soil holds too much water.",
  "Tip: Wipe the leaves with a damp cloth occasionally to remove dust.",
  "Tip: Consistent temperatures are better than big swings between day and night.",
  "Tip: Avoid cold drafts and air vents, which can stress your plant.",
  "Tip: Many cacti love a cool dry winter, which encourages spring blooms.",
  "Tip: If your cactus tips start browning, the air might be too dry.",
  "Tip: Misting is usually not needed for cacti — they absorb moisture through roots.",
  "Tip: New growth in spring is a sign your cactus is thriving.",
  "Tip: Rotate your pot a quarter turn every few weeks for even growth.",
  "Tip: Always wash your hands after handling cacti with fine glochids.",
  "Tip: A humidity tray is rarely needed, but good airflow always helps.",
  "Tip: Clay pots help wick away moisture and are great for cacti.",
  "Tip: Too much fertilizer can burn roots — less is more.",
  "Tip: If roots grow out of the drainage hole, it's time to repot.",
  "Tip: Checking the soil with your finger is more reliable than a fixed schedule.",
  "Tip: Cacti store water in their stems, so a little neglect is safer than too much attention.",
  "Tip: Terracotta pots dry out faster than plastic ones, which helps keep the soil from staying soggy.",
  "Tip: Use room-temperature water rather than very cold water.",
  "Tip: Slightly wrinkled skin can mean your cactus is thirsty, especially if the soil is completely dry.",
  "Tip: Cacti grow slowly, so don't worry if you don't see changes for weeks.",
  "Tip: Wear thick gloves or use folded newspaper when moving a spiky cactus.",
  "Tip: A cactus that stretches thin and leans toward the window may not be getting enough light.",
  "Tip: Wait several days after repotting before watering so any damaged roots can heal.",
  "Tip: Most cacti only need fertilizer a few times in the growing season, and none in winter.",
  "Tip: Check the base of your cactus now and then for soft or dark spots, which can be early signs of rot.",
  "Tip: Small white cottony spots can be mealybugs. Dab them with a cotton swab dipped in rubbing alcohol.",
  "Tip: Pick a spot with steady light instead of moving your cactus around often.",
  "Tip: If your sensor shows very low moisture for days, check that it is still pushed firmly into the soil.",
  "Tip: Soil moisture readings change slowly after watering, so give it a little time before checking again.",
  "Tip: Keep the sensor's metal probe clean, since dirt or mineral build-up can skew moisture readings.",
  "Tip: Low moisture is normal for many cacti, so compare it with how your plant looks before watering.",
];

export default cactusTips;
